- README.md
- docs/config.md
- docs/design/config_ng.md
> Add Config API documentation

- README.md
Update in-development message in README
Fixes #
```release-note
None
```
> Update in-development message in README

- go.work
Adding this file helps the editors to understand there are multiple go modules within this workspace and `gopls` process the workspace correctly.
Reference: https://github.com/golang/tools/blob/master/gopls/doc/workspace.md#multiple-modules
Fixes #
```release-note
```
> Add `go.work` file to the repository

- README.md
Update in-development notice in readme
```release-note
None
```
> Update in-development notice

- .github/workflows/compatibility_tests.yaml
- .github/workflows/publish_compatibility_tests_results.yaml
- .gitignore
- Makefile
- test/compatibility/docs/cross-version-api-compatibility.md
- test/compatibility/framework/executer/testcase_executer.go
> Compatibility tests results

- README.md
- test/compatibility/framework/compatibilitytests/context/context_test.go
> DONOTMERGE :Test GitHub badge for workflow

- config/cli_options_nextgen.go
- config/cli_options_nextgen_test.go
- config/config_keys.go
- config/types/clientconfig_types.go
This PR add API for CEIP Opt-in configuration. 
The new config parameter is added in the tanzu config-ng.yaml as shown below
```
cli:
ceipOptIn: "false"
```
Fixes #43 
Unit tests and CI passed
```release-note
Add API for CEIP Opt-In configuration
```
> Add APIs for CEIPOptIn configuration

- README.md
- docs/config.md
- test/compatibility/docs/cross-version-api-compatibility-framework.md
- test/compatibility/docs/cross-version-api-compatibility.md
- Update documentation to list all available Runtime Config APIs
- Update documentation for Cross-version API compatibility testing 
Fixes #
Run `make doc-lint` to verify the md files are valid.
```release-note
```
> Update documentation for Config APIs and Cross-version API compatibility testing

- .github/workflows/compatibility_tests.yaml
- README.md
- Add GitHub status badge for cross-version API compatibility tests.
- The status updated on event push on default branch i.e main. When a new commit is pushed to main branch the status of this badge updates as per workflow status.
- Clicking on badge will navigate to the workflow - branch: main and event push
Fixes #
Status Badge will be displayed as below
https://github.com/mpanchajanya/tanzu-plugin-runtime/tree/compatibility-test-results-badge
```release-note
```
> Add GitHub badge for compatibility tests workflow

- README.md
- docs/config.md
> Update links, reformat text

- CONTRIBUTING.md
- README.md
- docs/community/support.md
- docs/config.md
Add support doc, update links
Fixes #N/A
```release-note
```
> Add support doc, update links

- .github/workflows/release.yaml
This is the same workflow that was used on the release-0.80 branch, with the additions that
- we support releasing pre-release tags
- release notes generation starts checking from v0.0.1. after the first release we will restore the delta computation to use the last tag.
Fixes #N/A
```release-note
```
> Add release workflow to produce github release on tag

- README.md
Update development notice to account for alpha release.
> Update development notice

- .github/workflows/compatibility_tests.yaml
This was found by @anujc25 in https://github.com/vmware-tanzu/tanzu-plugin-runtime/pull/58#issuecomment-1521407349
The `Cross-version API Compatibility Tests` would only run for PRs that changed a file in the root directory of the repository.
We want those tests to run in all PRs so this commit removes the "path" restriction for running those tests.
Fixes #59
Let CI run and see that the `Cross-version API Compatibility Tests` run.
```release-note
```
> Run Compatibility tests on all PRs

- plugin/types.go
- Migrate the `DefaultFeatureFlags` field into PluginDescriptor struct to enable plugins to set default feature flags in config yaml file
Fixes #
- With default feature flags Verified plugin creation , build, install on local
Using Tanzu binary build using the TZC latest main branch code
and replaced the TZR local change that includes DefaultFeatureFlags in PluginDescriptor 
`replace github.com/vmware-tanzu/tanzu-plugin-runtime => ../tanzu-plugin-runtime
`
Steps performed
```
mpanchajanya@mpanchajanF09MK ~/v/r/tanzu-cli (default_feature_flags)> tanzu plugin install builder
[i] Installing plugin 'builder:v0.90.0-alpha.0' with target 'global'
[ok] successfully installed 'builder' plugin
mpanchajanya@mpanchajanF09MK ~/v/r/tanzu-cli (default_feature_flags)> tanzu builder init hello-world
? …
```
> Add DefaultFeatureFlags inot PluginDescriptor to enable plugins to set default feature flags in config file

- test/compatibility/core/api_constants.go
- test/compatibility/core/validators.go
- test/compatibility/framework/compatibilitytests/common/test_helpers.go
- test/compatibility/framework/compatibilitytests/featureflags/featureflags_suite_test.go
- test/compatibility/framework/compatibilitytests/featureflags/featureflags_test.go
- test/compatibility/framework/featureflags/feature_commands.go
- test/compatibility/framework/featureflags/feature_helpers.go
- test/compatibility/framework/featureflags/feature_options.go
- test/compatibility/framework/featureflags/feature_validators.go
- test/compatibility/testplugins/runtime-test-plugin-latest/cmd/trigger_apis.go
- test/compatibility/testplugins/runtime-test-plugin-latest/cmd/trigger_feature_apis.go
- test/compatibility/testplugins/runtime-test-plugin-latest/cmd/trigger_feature_apis_test.go
- test/compatibility/testplugins/runtime-test-plugin-v0_11_6/cmd/trigger_apis.go
- test/compatibility/testplugins/runtime-test-plugin-v0_11_6/cmd/trigger_feature_apis.go
- test/compatibility/testplugins/runtime-test-plugin-v0_11_6/cmd/trigger_feature_apis_test.go
- test/compatibility/testplugins/runtime-test-plugin-v0_25_4/cmd/trigger_apis.go
- test/compatibility/testplugins/runtime-test-plugin-v0_25_4/cmd/trigger_context_apis_test.go
- test/compatibility/testplugins/runtime-test-plugin-v0_25_4/cmd/trigger_feature_apis.go
- test/compatibility/testplugins/runtime-test-plugin-v0_25_4/cmd/trigger_feature_apis_test.go
- test/compatibility/testplugins/runtime-test-plugin-v0_25_4/cmd/trigger_server_apis.go
- test/compatibility/testplugins/runtime-test-plugin-v0_28_0/cmd/trigger_apis.go
- test/compatibility/testplugins/runtime-test-plugin-v0_28_0/cmd/trigger_context_apis_test.go
- test/compatibility/testplugins/runtime-test-plugin-v0_28_0/cmd/trigger_feature_apis.go
- test/compatibility/testplugins/runtime-test-plugin-v0_28_0/cmd/trigger_feature_apis_test.go
- Added Config Features APIs compatibility tests  for SetFeature, IsFeatureEnabled, DeleteFeature APIs for Runtime libraries latest, v0.28.0, v0.25.4, v0.11.6.
- Added helper methods to create API Commands, Validators to validate input and outputOptions.
- Extended the testplugins implementation to trigger Feature APIs.
- Added Default helper functions to create the input and output options data for command creation
Detailed Info:
`test/compatibility`
`core/api_constants.go` -> Added Feature Flag APIs names
`framework` changes
`compatibility-tests/featureflags` -> Add compatibility tests for feature flag APIs
`featureflags` directory to provide functions to create api commands and validations to help write compatibility tests for feature flags APIs
`testplugins` changes
Add Implementation …
> Cross-version API Compatibility tests - Feature flags API

- test/compatibility/core/api_constants.go
- test/compatibility/framework/compatibilitytests/clidiscoverysources/cli_discoverysources_test.go
- test/compatibility/framework/compatibilitytests/context/context_test.go
- test/compatibility/framework/compatibilitytests/contextserver/context_and_server_test.go
- test/compatibility/framework/compatibilitytests/featureflags/featureflags_test.go
- test/compatibility/framework/compatibilitytests/legacyclientconfig/legacyclientconfig_suite_test.go
- test/compatibility/framework/compatibilitytests/legacyclientconfig/legacyclientconfig_test.go
- test/compatibility/framework/featureflags/feature_helpers.go
- test/compatibility/framework/legacyclientconfig/legacy_clientconfig_helpers.go
- test/compatibility/framework/legacyclientconfig/legacyclientconfig_commands.go
- test/compatibility/framework/legacyclientconfig/legacyclientconfig_options.go
- test/compatibility/framework/types/cfg_options.go
- test/compatibility/framework/validators/testcase_validator.go
- test/compatibility/testplugins/runtime-test-plugin-latest/cmd/parser.go
- test/compatibility/testplugins/runtime-test-plugin-latest/cmd/trigger_apis.go
- test/compatibility/testplugins/runtime-test-plugin-latest/cmd/trigger_legacyclientconfig_apis.go
- test/compatibility/testplugins/runtime-test-plugin-v0_11_6/cmd/parser.go
- test/compatibility/testplugins/runtime-test-plugin-v0_11_6/cmd/trigger_apis.go
- test/compatibility/testplugins/runtime-test-plugin-v0_11_6/cmd/trigger_env_apis_test.go
- test/compatibility/testplugins/runtime-test-plugin-v0_11_6/cmd/trigger_legacyclientconfig_apis.go
- test/compatibility/testplugins/runtime-test-plugin-v0_25_4/cmd/parser.go
- test/compatibility/testplugins/runtime-test-plugin-v0_25_4/cmd/trigger_apis.go
- test/compatibility/testplugins/runtime-test-plugin-v0_25_4/cmd/trigger_env_apis_test.go
- test/compatibility/testplugins/runtime-test-plugin-v0_25_4/cmd/trigger_legacyclientconfig_apis.go
- test/compatibility/testplugins/runtime-test-plugin-v0_28_0/cmd/parser.go
- test/compatibility/testplugins/runtime-test-plugin-v0_28_0/cmd/trigger_apis.go
- test/compatibility/testplugins/runtime-test-plugin-v0_28_0/cmd/trigger_legacyclientconfig_apis.go
- Added Legacy Client Config APIs compatibility tests  for GetClientConfig, StoreClientConfig APIs for Runtime libraries latest, v0.28.0, v0.25.4, v0.11.6
- Added helper methods to create API Commands, Validators to validate input and outputOptions.
- Extended the testplugins implementation to trigger Legacy Client Config APIs.
- Added Default helper functions to create the input and output options data for command creation.
-  Updated existing tests with the new legacy client config apis liek feature, env tests
Detailed Info:
`test/compatibility`
`core/api_constants.go` -> Added  Legacy Client Config APIs names
`framework` changes
`compatibility-tests/legacyclientconfig` -> Add compatibility tests for  Legacy Client Config APIs
`legacyclientconfig` directory to provide functions to …
> Cross-version API Compatibility tests - GetClientConfig and StoreClientConfig APIs

- test/compatibility/core/api_constants.go
- test/compatibility/core/helpers_test.go
- test/compatibility/core/parsers_test.go
- test/compatibility/docs/cross-version-api-compatibility.md
- test/compatibility/framework/compatibilitytests/context/context_test_helpers.go
- test/compatibility/framework/compatibilitytests/metadata/metadata_test.go
- test/compatibility/framework/compatibilitytests/server/server_suite_test.go
- test/compatibility/framework/compatibilitytests/server/server_test_helpers.go
- test/compatibility/framework/context/context_commands.go
- test/compatibility/framework/context/context_commands_test.go
- test/compatibility/framework/context/context_options.go
- test/compatibility/framework/context/context_validators.go
- test/compatibility/framework/metadata/metadata_helpers.go
- test/compatibility/framework/metadata/metadata_options.go
- test/compatibility/framework/server/server_commands.go
- test/compatibility/framework/server/server_commands_test.go
- test/compatibility/framework/server/server_options.go
- test/compatibility/framework/server/server_validators.go
- test/compatibility/framework/types/cfg_metadata_options.go
- test/compatibility/testplugins/runtime-test-plugin-latest/cmd/trigger_apis.go
- test/compatibility/testplugins/runtime-test-plugin-latest/cmd/trigger_context_apis_test.go
- test/compatibility/testplugins/runtime-test-plugin-latest/cmd/trigger_server_apis_test.go
- test/compatibility/testplugins/runtime-test-plugin-v0_11_6/cmd/trigger_apis.go
- test/compatibility/testplugins/runtime-test-plugin-v0_11_6/cmd/trigger_server_apis_test.go
- test/compatibility/testplugins/runtime-test-plugin-v0_25_4/cmd/trigger_apis.go
- test/compatibility/testplugins/runtime-test-plugin-v0_25_4/cmd/trigger_context_apis_test.go
- test/compatibility/testplugins/runtime-test-plugin-v0_25_4/cmd/trigger_server_apis_test.go
- test/compatibility/testplugins/runtime-test-plugin-v0_28_0/cmd/trigger_apis.go
- test/compatibility/testplugins/runtime-test-plugin-v0_28_0/cmd/trigger_context_apis_test.go
- test/compatibility/testplugins/runtime-test-plugin-v0_28_0/cmd/trigger_server_apis_test.go
- Clean up some of the framework code
- Update documentation
Fixes #
```
make compatibility-tests
Ginkgo ran 8 suites in 35.302284375s
Test Suite Passed
```
```release-note
```
> Cross-version API compatibility tess - cleanup

- config/cli_options_nextgen.go
- config/cli_options_nextgen_test.go
- config/cli_options_telemetry.go
- config/cli_options_telemetry_test.go
- config/config_keys.go
- config/conversion.go
- config/types/clientconfig_types.go
This PR adds configuration APIs for Telemetry configuration
Fixes #79 
Unit tests and CI checks passed
```release-note
Add configuration APIs for Telemetry configuration
```
> Add config APIs for Telemetry configuration

- config/cli_options_telemetry_test.go
- config/types/clientconfig_types.go
- docs/config.md
This PR adds `cspOrgID` and `entitlementAccountNumber` to the telemetry options in the config
Fixes #
Unit tests and CI checks passed
```release-note
Add CSPOrgID and EntitlementAccountNumber to telemetry options in the config 
```
> Add CSPOrgID and EntitlementAccountNumber to telemetry options in the config 

- log/logger_test.go
Add additional unit test based on the review comments: https://github.com/vmware-tanzu/tanzu-plugin-runtime/pull/83
Fixes #
- Run unit tests as part of CI
```release-note
None
```
> Add additional unit test for expose log with TANZU_CLI_LOG_LEVEL

- log/logger.go
- log/logger_test.go
Cherry-pick: #83 #85
These are PRs from @anujc25 
Fixes # N/A
`git diff main` is empty, confirming that these cherry-picks bring us up-to-date with the recent fixes on `main`
Let CI run
```release-note
Expose the `TANZU_CLI_LOG_LEVEL` environment variable to control the log level
```
> [release-1.0] Cherrypick: Expose the `TANZU_CLI_LOG_LEVEL` environment variable to control the log level

- config/envs.go
- config/envs_test.go
- config/metadata_settings_api.go
This PR is to make sure the `<value>` for the `tanzu config set <key> <value>` is not mandatory, the `<value>` can be empty string.
Fixes #
Unit test cases added.
```release-note
```
> Allow empty value for config set

- hack/scripts/lint-all-plugins.sh
- plugin/lint/cli-wordlist.yml
The global taxonomy wordlist is grossly out-of-date. 
This changes updates it to account of the new terms/flags introduced since the last update.
Note that this change does not immediate affect the lint command output of already-released plugins. 
For a plugin to have more accurately reflection of its lint output, the plugin will have to be rebuilt and linked with the version of the tanzu-plugin-runtime that includes the updated wordlist. 
Also: includes a script `lint-all-plugins.sh` to produce the lint output for all installed plugins.
The above-mentioned script was used to produce the terms/flags that are flagged. The output is then audited for any blatant violations, and the rest merged back into the global word list.
Fixes #N/A
`make all`
```release-note
Update terms/flags list …
```
> Update CLI command taxonomy word list

- config/contexts.go
- config/contexts_test.go
- config/types/clientconfig.go
- config/types/clientconfig_helper.go
- test/plugins/helloworld/go.sum
This PR is to add  "ucp" as new TargetType to indicate the type of Context used to interact with a Unified Control Plane endpoint
Fixes #
Unit test and CI passed
```release-note
Add Target type "ucp" to indicate the type of Context used to interact with a Unified Control Plane endpoint
```
> Add Target type "ucp" to indicate the type of Context used to interact with a Unified Control Plane endpoint

- .github/workflows/compatibility_tests.yaml
- .github/workflows/main.yaml
Make sure CI is trigger on changes to release branches as well.
Fixes #
will monitor CI
```release-note
```
> Update branch patterns to trigger CI on

- README.md
Remove pre 1.0 alpha notice as was done in the release-1.1 branch
Fixes # N/A
```release-note
```
> [Cherry-pick] Remove pre 1.0 alpha notice

- .github/workflows/release.yaml
The hardcode was there during a period when it made sense to include all the release notes for each version released.
Now that 1.0 has been released, release notes should be incremental and relative to the last release.
Fixes #
```release-note
```
> Remove hardcode of source commit for release notes

- test/compatibility/core/api_constants.go
- test/compatibility/framework/compatibilitytests/context/context_test.go
- test/compatibility/framework/context/context_commands.go
- test/compatibility/framework/context/context_helpers.go
- test/compatibility/framework/context/context_options.go
- test/compatibility/framework/context/context_validators.go
- test/compatibility/framework/types/cfg_options.go
- test/compatibility/framework/types/cfg_validators.go
- test/compatibility/testplugins/runtime-test-plugin-latest/cmd/trigger_apis.go
- test/compatibility/testplugins/runtime-test-plugin-latest/cmd/trigger_context_apis.go
This PR addes compatibility tests to validate k8s and tanzu active context mutual exclusion behavior
Fixes #
CI tests passed
```release-note
```
> Compatibility tests to validate k8s and tanzu active context mutual exclusion behavior

- config/context_server_test.go
- Update context server sync tests to include context type
Fixes #
- Verified make lint, make test, make all to make sure all pass
```release-note
```
> Update context server sync tests to include context type

- config/types/clientconfig.go
- config/types/clientconfig_types.go
- Deprecate IsManagementCluster field from Context struct
Fixes #
```release-note
```
> Deprecate IsManagementCluster field

- component/output.go
- component/output_spinner.go
- component/output_test.go
This PR is to revert the https://github.com/vmware-tanzu/tanzu-plugin-runtime/pull/148 changes
Fixes #
```release-note
```
> Revert "UX: Updated the output writer with text format (#148)"

- component/README.md
- component/output_spinner.go
- component/output_spinner_test.go
- Do not return error for `NewOutputWriterSpinner` API
Fixes #
```release-note
None
```
> Do not return error for `NewOutputWriterSpinner` API

- .github/workflows/release.yaml
For more info see:
[discussion on SO](https://stackoverflow.com/questions/75024695/github-actions-how-to-handle-a-in-json-when-passing-it-across-steps)
Fixes #
```release-note
```
> Fix shell interpolation issues in get-new-contributors step

- .github/workflows/release.yaml
Fixes #
Trigger updated workflow in the test debug branch
https://github.com/vmware-tanzu/tanzu-plugin-runtime/actions/runs/8174339415/job/22348894217
```release-note
```
> Fix typo in release workflow

- config/contexts_test.go
- config/tanzu_context.go
- config/tanzu_context_test.go
This PR is to enhance `GetTanzuContextActiveResource` API to include organization name retrieval
Fixes #
Unit tests and CI passed
```release-note
Enhance GetTanzuContextActiveResource API to include organization name retrieval
```
> Enhance GetTanzuContextActiveResource API to include organization name retrieval

- config/contexts_test.go
- config/tanzu_context.go
- config/tanzu_context_test.go
- plugin/generate_docs.go
- plugin/generate_docs_test.go
- plugin/invoke_context.go
- plugin/invoke_context_test.go
- plugin/plugin.go
- plugin/usage.go
- plugin/usage_test.go
> Cherry pick to release-1.3 for alpha.4

- plugin/generate_docs.go
- plugin/generate_docs_test.go
Ensure that the inherited flags of each command being cloned for remapping is captured in the command itself prior to the clone. This enables the correct generation of the
'### Options inherited from parent commands'
section in the markdown file.
Fixes #
See updated unit tests.
```release-note
Ensure inherited flags are captured in generate-docs
```
> Ensure inherited flags are captured in generate-docs

- CONTRIBUTING.md
- Remove dead cla.vmware.com links
Fixes #
```release-note
None
```
> Remove dead links from the documents

- config/clientconfignextgen_lock.go
- config/lock.go
- config/lock_test.go
- config/metadata_lock.go
- go.mod
- go.sum
This PR updates the file locking go module dependency
Fixes #
- CI and Unit tests passed.
- Used project plugin and updated the go.mod to point to the local tanzu-plugin-runtime and compiled the project plugin. Later ran the `tanzu project use` command which would update the CLI configuration file (after acquiring the locks using the new library) and also ran the `tanzu context list` command (which is using the old plugin-runtime version without the new locklibrary change) which access the CLI configuration file(after acquiring the locks) in parallel so as to verify the new library locking don't have compatibility issues with the CLI/plugins using the old locking library. Below are the snapshots for the tests and they ran successfully.
```release-note
```
> Update the file locking module dependency

- client/hub/client_test.go
- client/hub/testing/README.md
- client/hub/testing/operations.go
- client/hub/testing/server.go
- client/hub/types.go
- config/clientconfignextgen_lock.go
- config/lock.go
- config/metadata_lock.go
- Cherry-pick for the release 1.4.2 
Fixes #
```release-note
Fix file lock issue on Windows
Make OperationName optional for Hub Client requests. Improvements to the Hub client unit test framework
```
> Cherry-pick for the release 1.4.2 

- config/tanzu_context.go
This is to supporting additional IDP types like UAA.
Fixes #
```release-note
```
> Add constants for auth-related fields of additionalMetaData

- client/hub/client.go
- component/select.go
- config/certs.go
- config/certs_test.go
- config/tanzu_context.go
- docs/config.md
> Cherry-picks for release-1.4.3

- client/hub/client.go
- Fix issue to not update DefaultTransport and use Clone
Fixes #
```release-note
Fix DefaultTransport getting updated when creating Tanzu Hub Client
```
> Fix DefaultTransport getting updated when creating Tanzu Hub Client

- client/hub/client.go
cherry-pick: #214
- Fix DefaultTransport getting updated when creating Tanzu Hub Client
Fixes #
```release-note
```
> [Cherry-pick 1.4] Fix DefaultTransport getting updated when creating Tanzu Hub Client

- client/hub/request.go
Fixes #
```release-note
Increases the GraphQL subscription client buffer size to 1MB to handle larger event chunks
```
> Increases the graphql subscription client buffer size to 1mb to handle larger event chunks

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
The repository https://github.com/vmware/.github became private today which broke our CI because we have a link to that repo.  To unblock our CI, the repo was made public again, but only temporarily.
To prepare for the repo to be private again, this PR:
- update the local CODE_OF_CONDUCT.md file to match the latest one from that repo
- updates the link in this repo to use the local CODE_OF_CONDUCT.md
Fixes # N/A
Let CI run
```release-note
Update CODE_OF_CONDUCT.md
```
> Update Code of Conduct
