config/types/clientconfig.go, config/types/clientconfig_helper.go, plugin/plugin.go, plugin/plugin_test.go, plugin/types.go, test/plugins/helloworld/main.go
This change updates the plugin contract to specify `target` information as part of the plugin descriptor. Old plugins will continue to work but new plugins using the latest plugin runtime will be enforced to provide target information as part of PluginDescriptor.
This change doesn't affect existing plugins because CLI is consuming this `target` field during the build time of the plugins and not during the runtime to determine the `target` of the plugin. So, once the plugins are already built, they should continue to work with the newer version of `tanzu-cli`.
Renames `TargetNone` to `TargetUnknown` and added another target `TargetGlobal`.
While installing the plugin this change will be made backward compatible.
Fixes #16
- Updated unit tests.
- Verified that the build fails if a user is …
=> Update PluginDescriptor to include the`target` field as part of the contract

.golangci.yaml, config/contexts.go, config/discovery_sources_node.go, config/legacy_clientconfig_factory.go, config/servers.go, config/types/clientconfig.go, config/types/clientconfig_types.go
- This PR marks all the server APIs for the configuration file as deprecated and suggests using context APIs instead.
- This PR also marks additional ClientConfig configurations that are deprecated and is not used by the core-cli as Deprecated
- The PR uses the standard deprecation syntax for the APIs as specified in https://go.dev/blog/godoc
> To signal that an identifier should not be used, add a paragraph to its doc comment that begins with "Deprecated:" followed by some information about the deprecation.
- The documentation site [pkg.go.dev](https://pkg.go.dev/) hides the documentation for deprecated identifiers behind a click of a "show" button.
- The [staticcheck](https://staticcheck.io/) tool reports use of deprecated identifiers
Fixes #
```release-note
Add Deprecation annotation …
```
=> Add Deprecation annotation to the Deprecated APIs

.gitignore, Makefile, test/compatibility/core/validators_test.go, test/compatibility/docs/cross-version-api-compatibility-framework.md, test/compatibility/docs/cross-version-api-compatibility.md, test/compatibility/framework/compatibilitytests/context/context_suite_test.go, test/compatibility/framework/compatibilitytests/context/context_test.go, test/compatibility/framework/compatibilitytests/context/context_test_helpers.go, test/compatibility/framework/compatibilitytests/contextserver/context_and_server_test.go, test/compatibility/framework/compatibilitytests/contextserver/contextserver_suite_test.go, test/compatibility/framework/compatibilitytests/server/servers_suite_test.go, test/compatibility/framework/executer/testcase_executer.go, test/compatibility/testplugins/runtime-test-plugin-latest/cmd/parser.go, test/compatibility/testplugins/runtime-test-plugin-latest/cmd/trigger_server_apis.go, test/compatibility/testplugins/runtime-test-plugin-latest/cmd/trigger_server_apis_test.go, test/compatibility/testplugins/runtime-test-plugin-latest/go.mod, test/compatibility/testplugins/runtime-test-plugin-v0_25_4/cmd/trigger_apis.go, test/compatibility/testplugins/runtime-test-plugin-v0_25_4/cmd/trigger_server_apis.go
Follow up PR addresses
- Reduce verbose noise in Tests.
- Added COMPATIBILITY_TEST_VERBOSE configurable variable to run compatibility tests.
- Added Documentation for test results and outputs
- Test Output in the GH workflow will display all API test suites that are run.
- Added Context API tests involving multiple context objects.
- Added Combination tests for Context and Server APIs.
Fixes #
- Run Unit tests for test/compatibility
- Build and Run compatibility tests using below command and make sure all tests pass
`make compatibility-tests`
Output: 
More details on test output can be found from the Github workflow that is run on the PR https://github.com/vmware-tanzu/tanzu-plugin-runtime/actions/runs/4495795430/jobs/7909811037?pr=26
For more details on Cross-version API compatibility …
=> Cross-version API Compatibility - Follow up changes on test results and additional tests

test/framework/framework.go
- Fix the Test plugin to include Target by default
Without the fix, when we execute the test plugin binary with `tanzu test plugin hello-world` it throws the below error: `invalid PluginDescriptor specified: plugin "hello-world-test": target is not valid`
Fixes #48
```release-note
Fix the Test plugin to include Target by default
```
=> Fix Test plugin to include Target by default

test/framework/README.md
Add docs for plugin test helper functions
Fixes #
make doc-lint
```release-note
```
=> Add docs for framework plugin test helpers

.github/workflows/compatibility_tests.yaml, test/compatibility/core/api_constants.go, test/compatibility/docs/cross-version-api-compatibility-framework.md, test/compatibility/docs/cross-version-api-compatibility.md, test/compatibility/framework/compatibilitytests/common/test_helpers.go, test/compatibility/framework/compatibilitytests/context/context_test.go, test/compatibility/framework/compatibilitytests/context/context_test_helpers.go, test/compatibility/framework/compatibilitytests/contextserver/context_and_server_test.go, test/compatibility/framework/compatibilitytests/server/server_test.go, test/compatibility/framework/compatibilitytests/server/server_test_helpers.go, test/compatibility/framework/validators/testcase_validator.go, test/compatibility/testplugins/runtime-test-plugin-latest/cmd/trigger_apis.go, test/compatibility/testplugins/runtime-test-plugin-v0_11_6/cmd/trigger_apis.go, test/compatibility/testplugins/runtime-test-plugin-v0_25_4/cmd/trigger_apis.go, test/compatibility/testplugins/runtime-test-plugin-v0_28_0/cmd/trigger_apis.go
- Refactored the tests using updated test helpers.
- Added individual API test helpers for Servers and Context APIs to be reuse in test cases.
Fixes #
- Run Unit tests for test/compatibility
- Build and Run compatibility tests using below command and make sure all tests pass
`make compatibility-tests`
More details on test output can be found from the Github workflow that is run on this PR https://github.com/vmware-tanzu/tanzu-plugin-runtime/actions/runs/4495795430/jobs/7909811037?pr=26
For more details on Cross-version API compatibility testing refer to https://github.com/vmware-tanzu/tanzu-plugin-runtime/blob/main/test/compatibility/docs/cross-version-api-compatibility.md
```release-note
```
=> Cross-version API Compatibility - Cleanup Test Helper functions

config/cli_repositories.go, config/clientconfig_factory.go, config/clientconfignextgen_factory_test.go, config/contexts.go, config/conversion.go, config/discovery_sources_node.go, config/metadata_factory.go, config/servers.go
This does some code cleanup to take advantage of generics to avoid code duplication.
It replaces the 6 different `convert*ToNode(..)` functions to using a single one with generics: `convertObjectToNode[T](..)`.
Fixes #
Built the CLI using this change and did a `tz config get` after creating contexts.
```release-note
```
=> Use generics to convert objects to config nodes

config/cli_discovery_sources.go, config/cli_discovery_sources_it_test.go, config/cli_discovery_sources_test.go, config/config_factory_test.go, config/legacy_clientconfig_factory.go, config/legacy_clientconfig_factory_test.go, config/patchstrategy_it_test.go, config/types/clientconfig_types.go
This PR moves the DiscoverySources configuration section from "clientOptions.cli.discoverySources" to "cli.discoverySources". The actual handling of discovery sources is kept the same; it is just the section of the configuration file in which they are stored that is moved.
This change is necessary as plugins built with the previous version of the runtime library would set a "default" discovery source which the new independent CLI should not use; by moving the discovery sources section in the config file, the new CLI can ignore the old section and trust that the new section only contains valid sources, even when older plugins are used.
Note that we don't yet modify the CLI to make use of this change but simply start by making sure the `tz plugin source` commands properly work with the new …
=> Move the DiscoverySources config section

config/certs.go, config/certs_test.go, config/config_keys.go, config/conversion.go, config/types/clientconfig_types.go
This PR is to add configuration APIs for custom certificate configuration
The sample configuration is shown below which would be added to the configuration file (config-ng.yaml)
```
certs:
- hostName: localhost:9876
skipCertVerify: "true"
insecure: "true"
caCertData: <REDACTED>
```
Fixes #
Unit tests and CI passed
```release-note
Add configuration APIs for Certificate configuration
```
=> Add configuration APIs for Certificate configuration

component/prompt.go, component/prompt_test.go
- Enable validations on prompts 
- Implemented WithValidator() to set validator functions
- Added couple of custom validators NoUpperCase(), NoOnlySpaces()
Fixes #
- Added unit test to verify the changes including built in validators and custom validators
- Verified importing the tzr changes into tzc locally and tested tanzu context and tanzu login command with new validators required and NoOnlySpaces
Below testing show Required and no only spaces validators in action
```
mpanchajanya@mpanchajanF09MK ~/v/r/tanzu-cli (bug-fix-do-not-allow-empty-context-names)> tanzu context create
? Select context creation type Control plane endpoint
X Sorry, your reply was invalid: value contains only spaces
? Enter control plane endpoint test
X Sorry, your reply was invalid: value contains only spaces
? …
```
=> Add validators functionality to prompts

config/certs.go, config/cli_discovery_sources.go, config/cli_discovery_sources_test.go, config/cli_options.go, config/cli_options_test.go, config/cli_repositories.go, config/contexts.go, config/contexts_it_test.go, config/contexts_test.go, config/discovery_sources_node.go, config/envs.go, config/envs_test.go, config/features.go, config/features_test.go, config/metadata_api.go, config/metadata_settings_api.go, config/servers.go
-  Without these empty checks the config items like contexts, servers etc duplicate in config files when name is empty
- Added empty value checks for config APIs to return error when encounter an empty value.
Fixes #
Added Unit tests
Updated the Integration tests
Cross-version compatibility tests passed
```release-note
added empty checks for config apis. Config APIs now doesn't allow bad data to persist in the config yaml files
```
=> Bug Fix:  Add empty checks for config APIs

config/cli_options_nextgen.go, config/cli_options_nextgen_test.go, config/clientconfig_factory_test.go, config/clientconfig_test.go, config/clientconfignextgen_factory_test.go, config/config_keys.go, config/metadata_factory_test.go, config/types/clientconfig_types.go
Implement {Get,Set}EULAStatus
to read/write user's EULA acceptance status.
`tanzu eula show`
Shows agreement text AND prompts for user to accept terms.
Displays short text summarizing general terms, with link to online URL with more details.
`tanzu eula accept`
bypasses the interactive display of the terms, and accepts them immediately. 
This is useful for automation use cases. 
Also:
- small number of unit tests are taking >90% of run time (upwards of 1.5 minutes), configured them so they are skippable with go test -short.
Fixes #N/A
Ran updated unit tests.
```release-note
None
```
=> Add EULA Acceptance support

plugin/plugin.go, plugin/root.go, plugin/usage.go
- Update newRootCmd function to add target annotation for plugin root command
-  Update plugin execute function to propagate the target annotation from parent to all children commands
- Update the usage template to include target annotation
Few caveats:
- This fix addresses the plugins built with latest runtime after this fix. Existing plugins using previous runtime will not pick this change and issue still exists.
- Plugins need to be updated to latest runtime to pick this change.
- With kubernetes targeted plugins
Both Commands `tz hello create -h `and `tz k8s hello create -h` will display the help usage with target kubernetes
```
mpanchajanya@mpanchajanF09MK ~> tz hello create -h
Tanzu CLI plugins to create
Usage:
tanzu kubernetes hello create [flags]
tanzu kubernetes hello create …
```
=> Bug fix: Update plugin usage to include target

config/cli_options.go, config/cli_repositories.go, config/legacy_clientconfig.go, config/legacy_clientconfig_factory.go, config/types/clientconfig.go, config/types/clientconfig_types.go
- Deprecate legacy config apis to encourage use of new config next gen apis.
APIs related to CLIOptions are deprecated to use CoreCLIOptions
Fixes #
make lint to verify no staticcheck issues
```release-note
legacy config apis are marked for deprecation . use new config next gen apis
```
=> Deprecate legacy config APIs

plugin/sync_plugins.go, plugin/sync_plugins_test.go
SyncPluginsForTarget will attempt to install plugins required by the active
Context of the provided target. This is most useful for any plugin
implementation which creates a new Context or updates an existing one as
part of its operation, and prefers that the plugins appropriate for the
Context are immediately available for use.
Note: This API is considered EXPERIMENTAL. Both the function's signature and
implementation are subjected to change/removal if an alternative means to
provide equivalent functionality can be introduced.
---
In addition: 
Check for alternative command invocation
Invoke what would be a hidden '_custom_command' command to obtain an
alternate means to perform, in this case, the plugin syncing operation.
This command is expected to fail at the moment, and the behavior …
=>  Provide experimental SyncPluginsForTarget API

config/config_keys.go, config/contexts.go, config/contexts_additionalmetadata_test.go, config/contexts_it_test.go, config/contexts_test.go, config/legacy_clientconfig_factory_test.go, config/nodeutils/helpers.go, config/nodeutils/helpers_test.go, config/nodeutils/merge_nodes.go, config/types/clientconfig_types.go
- At the moment, Tanzu Plugin Runtime - Context configuration does not provide a means to add any additional metadata.
This proposal introduces a new AdditionalMetadata map field to Context to be able to provide additional data for each context. This way we don't have to release a new version of runtime every time we add a new property to the context object.
Example: TMC will need to store a few additional properties for each context and the fields could change in future. In TMC Self-Managed with VCD's login flow, it requires "VCD org" and "VCD OIDC client ID" to be persisted in context, so that TMC Plugins can auto-refresh or re-trigger the token flow if needed when a TMC plugin command is called.
Example usage:
- Add two new properties to context
```
ctx := &Context {
Name: tanzu-ctx, …
```
=> Introduce additional metadata field to Context

log/logger.go, log/logger_test.go
Tanzu Plugin Runtime exposes a logger functionality and also allows logs to be displayed based on the different log levels.
It also exposes API to control the log level for external plugins.
However, we wanted the log levels to be controlled by the user at the runtime so that we can enable more logs for debugging purposes. This PR provides an environment variable `TANZU_CLI_LOG_LEVEL` to control the log level.
The default value of the Tanzu CLI log level is `3`. So any user wanting to see more debug logs should configure `TANZU_CLI_LOG_LEVEL` with value `>3`. 
Fixes #
* Manually tested the change.
* Added unit tests.
* Sample tests details mentioned under: https://github.com/vmware-tanzu/tanzu-cli/pull/437
```release-note
Expose the `TANZU_CLI_LOG_LEVEL` environment variable to control …
```
=> Expose `TANZU_CLI_LOG_LEVEL` environment variable to control the log level

plugin/sync_plugins.go, plugin/sync_plugins_test.go
The `TanzuPluginSyncForTarget` API is exposed to sync plugins as an experimental API.
* However, when this API is invoked by a plugin, `stdout` and `stderr` are returned as part of the API and are not actively written to the `stdout` or `stderr`. 
* Because of this it makes it feel like the CLI is stuck when installing plugins, especially when there large number of plugin that needs to be installed as part of plugin sync API giving subpar UX to the users.
This change exposes additional `CommandOptions` to configure the `outputWriter` and `errorWriter` using `WithOutputWriter` and `WithErrorWriter` options when invoking the `TanzuPluginSyncForTarget` API, along with writing the output directly to the `os.Stdout` and `os.Stderr` by default.
**Note:** Unlike before, the API will now write …
=> Update SyncPluginsForTarget API to allow configuring `stdout` and `stderr` externally

plugin/sync_plugins.go
- Fix the example for SyncPluginsForTarget in the function godoc
Addresses the comment: https://github.com/vmware-tanzu/tanzu-plugin-runtime/pull/88#discussion_r1297564391 that got overwritten by subsequent force push.
Fixes #
```release-note
None
```
=> Fix example for SyncPluginsForTarget in the function godoc

plugin/root.go, plugin/usage.go, plugin/usage_test.go
- Refactored the CmdTemplate help text to use the new go lang function that generated the help text templates.
- The same const is used CmdTemplate with internal implementation changed from text template to use go func.
- Additional fix to https://github.com/vmware-tanzu/tanzu-plugin-runtime/pull/92
Fixes #
- Added unit tests for each plugin target i.e global, k8s, tmc
Manual Testing 
**Global Test Plugin**
**_Before_**  
Usage text doesn't show the tanzu prefix
```
mpanchajanya@mpanchajanF09MK ~/v/r/tanzu-cli (main)> tanzu test -h
Test the CLI
Usage:
test [command]
Aliases:
test, t
Available Commands:
fetch         Fetch the plugin tests
push          Push the plugin tests
Flags:
-h, --help   help for test
Additional help topics:
test plugin        Plugin tests
Use "tanzu test [command] …
```
=> Update help text template to fix target usage

plugin/root.go, plugin/usage.go, plugin/usage_test.go
* Update help text template to fix target usage
* Add two spaces for tanzu command
* Convert the help template to go code
Signed-off-by: Marc Khouzam <kmarc@vmware.com>
* testing the lint and tests
* refactor the print help
* refactor the indentation
* Update check to HasPrefix from HasSuffix
* Update tests to include global flags and fetch --help command
* Update additional help topics section with tanzu and target prefix
* Revert additional help topics targeted prefix
* Deprecate CmdTemplate and introduce private cmdTemplate variable and update all usages
* Fix sub command unit tests by executing plugin instead of command
* Fix spacing in examples section and update tests
---------
Signed-off-by: Marc Khouzam <kmarc@vmware.com>
Co-authored-by: Marc Khouzam <kmarc@vmware.com>
(cherry …
=> Update help text template to fix target usage (#94)

README.md, config/plugin-owned.go, config/plugin-owned_test.go, docs/config.md
- Provide an API to manage plugin owned settings
Fixes #
- Added unit tests
Manually testing
- Triggered the new API in a test plugin to retrieve the plugins dir
```
**Test plugin with plugins command**
var pluginsCmd = &cobra.Command{
Use:   "plugin",
Short: "Plugin tests",
Run: func(cmd *cobra.Command, args []string) {
pluginsDir, err := configlib.GetTanzuPluginConfigDir()
if err != nil {
log.Fatal(err, "")
}
log.Info(pluginsDir)
},
}
mpanchajanya@mpanchajanF09MK ~ % tanzu test plugin
[i] /Users/mpanchajanya/.config/tanzu/plugins
mpanchajanya@mpanchajanF09MK ~ %
```
```release-note
Add new API to return config directory to manage plugin owned settings
```
=> Add API to manage plugin owned settings

component/output.go, component/output_test.go
```
Store outputwriter data as 2d array of interfaces
... instead of 2d array of strings done prior to this commit.
AddRow accepts a variatic list of interface{}s, yet immediately converts
each of them to their golang string representation.
This change retains these values as interface{}'s instead.
The idea is to delay any necessary conversion to the point when we are
actually rendering the values.
This is particular useful when rendering container values like
maps/lists in their valid YAML/JSON forms.
```
Fixes #102
make test
```release-note
OutputWriter's JSON/YAML outputs non-string tabular fields correctly
```
=> Data as interface in outputwriter

ucp/ucp.go, ucp/ucp_test.go
This PR adds the API to set UCP active resource for the given UCP context.
Changes summary:
- Added API to set active UCP resource for given UCP context. API would call the CLI command to set the active UCP resource for the given UCP context
Fixes #
Unit tests are passed.
Also ran few tests using the below test stub (in ucp.test.go) with ucp context("myucp") already created in CLI.
```
func TestSetUCPContextActiveResourceSample(t *testing.T) {
// Test updating the UCP context active resource to space
os.Setenv("TANZU_BIN", "/Users/pkalle/projects/tanzu-cli/artifacts/darwin/amd64/cli/core/v1.1.0-dev/tanzu-cli-darwin_amd64")
projectName := "projectA"
spaceName:="spaceA"
err := SetUCPContextActiveResource("myucp", projectName, spaceName)
assert.NoError(t, err)
}
```
Tested setting the UCP …
=> Add API to set active UCP resource for UCP context

config/contexts.go, config/contexts_test.go, test/compatibility/testplugins/runtime-test-plugin-latest/go.sum
This PR makes kubernetes and application-engine current contexts mutual exclusive, which means if the k8s context is set as current(active) the TAE context would be removed and vice-versa.
Fixes #114 
Unit tests and CI passed.
```release-note
Make kubernetes and application-engine type current contexts mutual exclusive
```
=> Make kubernetes and application-engine type current contexts mutual exclusive

component/README.md, component/output.go, component/output_spinner.go, component/output_test.go, plugin/lint/lint.go
This is followup on #103, updating it to provide the JSON/YAML rendering fix while retaining the existing behavior.
These provides additional customizability and subsumes the functionality of NewOutputWriter and NewOutputWriterWithSpinner, which are Deprecated.
By using `NewOutputWriterWithOptions`, `NewOutputWriterSpinnerWithOptions`,  JSON and YAML output will render nonstring types correctly. (See issue #102). For backward compatibility, callers that wish to retain the JSON/YAML output behavior of the deprecated APIs may update to use the new API counterparts, by additionally providing a WithAutoStringify() option in the OutputWriterOption list.
Fixes: #102
```release-note
NewOutputWriter and NewOutputWriterWithSpinner APIs are deprecated in favor of NewOutputWriterWithOptions and …
```
=> Implement new APIs NewOutputWriterWithOptions, NewOutputWriterSpinnerWithOptions

config/clientconfig_test.go, config/config_factory_test.go, config/contexts.go, config/contexts_it_test.go, config/contexts_test.go, config/conversion.go, config/conversion_test.go, config/legacy_clientconfig_factory.go, config/legacy_clientconfig_factory_test.go, config/servers.go, config/servers_it_test.go, config/types/clientconfig.go, config/types/clientconfig_helper.go, config/types/clientconfig_test.go, config/types/clientconfig_types.go, docs/config.md, plugin/sync_plugins.go, plugin/sync_plugins_test.go, tae/tae.go, tae/tae_test.go, test/compatibility/framework/compatibilitytests/context/context_test_helpers.go, test/compatibility/framework/compatibilitytests/legacyclientconfig/legacyclientconfig_test.go, test/compatibility/framework/legacyclientconfig/legacyclientconfig_options.go, test/compatibility/framework/types/cfg_options.go, test/compatibility/testplugins/runtime-test-plugin-latest/cmd/trigger_context_apis.go
**Background:**
* Today, Tanzu CLI does not have a concept of Context-Type and we use the same concept Target to represent different types of Context as well as how we group plugins under the Tanzu CLI command tree.
* In the existing Tanzu CLI code implementation, a single custom datatype Target is used to represent both the Context-Type and Target concept making both concepts tightly coupled.
* Today, Target also has some values like `global` which does not make sense as a Context-Type value and the code assumes that value cannot be a value of a Context-Type.
* Because of the above, Creating a new Target has the effect of representing a new type of context and groups a set of plugins, but sometimes one of the consequences is unintended.
**Change:**
* As part of this PR we are introducing …
=> Decouple the Target association with the Context object by introducing ContextType

config/contexts.go, config/contexts_test.go, docs/config.md
This API return a lists of Contexts matching the provided context type.
Fixes #
make test
```release-note
Add GetContextsByType API for retrieve the list of contexts matching a particular context type.
```
=> Add GetContextsByType API

plugin/info.go, plugin/info_test.go
On Darwin ARM64 machines, the CLI can install plugins using either an ARM64 or an AMD64 build, depending of plugin binary availability. Showing the arch type in the output of `tanzu <plugin> info` will help in troubleshooting.
Fixes # N/A
Build the builder plugin for both ARM64 and AMD64 using the plugin-runtime with this PR:
```
$ cd tanzu-cli
$ rm -rf artifacts
$ make plugin-build
```
```
$ tz plugin install --local-source artifacts/plugins/darwin/arm64 builder
[i] Installing plugin 'builder:v1.1.0-dev' with target 'global'
[ok] successfully installed 'builder' plugin
$ tz builder info
{"name":"builder","description":"Build Tanzu components","target":"global","version":"v1.1.0-dev","buildSHA":"1283b075b-dirty","digest":"","group":"Admin","docURL":"","completionType":0,"pluginRuntimeVersi …
```
=> Add arch type to the output of the plugin info cmd

config/cli_options_nextgen.go, config/cli_options_nextgen_test.go, config/config_keys.go, config/types/clientconfig_types.go
Add API to get and set accepted EULA versions
This change adds APIs to get set a new eulaAcceptedVersions field in the config ng file
```
cli:
...
eulaAcceptedVersions: v1.0.0,v1.0.1,v1.2.0
```
The field will contain a string of one or more semver sorted versions separated by comma
The field will be used to register the EULA versions accepted.
Fixes #
Ran added unit tests.
```release-note
Adds API to get and set accepted EULA versions from/to the config file
```
=> Add API to get and set accepted EULA versions

config/context_server_test.go
- Add context and server sync tests
- Tests validating the syncing behaviours between contexts and servers when only context is present and no servers are in config yml and vice versa
Fixes #
make test
```release-note
Added context and server sync tests
```
=> Add context and server sync tests

config/tanzu_context.go, config/tanzu_context_test.go
- Updates `tanzu` context APIs to support ClusterGroup
- **Updates the `GetKubeconfigForContext` to make it more generalized. Users can pass resource options as `opts` argument.**
```
- func GetKubeconfigForContext(contextName, projectName, spaceName string) ([]byte, error) {
+ func GetKubeconfigForContext(contextName string, opts ...ResourceOptions) ([]byte, error) {
```
Example usage of `GetKubeconfigForContext`:
```
GetKubeconfigForContext("context-name-1", ForProject("test-project"))
GetKubeconfigForContext("context-name-1", ForProject("test-project"), ForClusterGroup("clustergroup1"))
GetKubeconfigForContext("context-name-1", ForProject("test-project"), ForSpace("space1"))
```
- **Updates the `SetTanzuContextActiveResource` to make it more generalized that now takes the …
=> Update `tanzu` context APIs to support ClusterGroup

component/colorable-tty.go
This pull request adds the new green color in the component package. This new API helps to highlight the UX by providing a green color option.
Fixes #
Tested in local, here is the output:
```release-note
```
=> UX: Add new green color

config/clientconfig_factory.go, config/features.go, config/features_test.go, config/legacy_clientconfig_factory.go, config/legacy_clientconfig_filesystem.go, config/types/clientconfig.go, config/types/clientconfig_features.go, config/types/clientconfig_features_test.go
- Added New Feature APIs
-  GetAllFeatureFlags
- ConfigureDefaultFeatureFlags
- Added new ClientConfig methods
- IsConfigFeatureActivated
- IsFeatureFlagExists
- GetAllFeatureFlags 
- Deprecate legacy methods and variables
Fixes #
- Added new tests for the new APIs
```release-note
```
=> Update feature flags apis

component/output.go, component/output_spinner.go, component/output_test.go
This pull request updates the output writer to include text format support and replaces `fmt.Fprintln` with `fmt.Fprint` in the spinner output. If the API user wants to add a new line at the end of the text or message, it can be appended.
Fixes #
Unit tests are added
Also manual test has done by adding the text format:
```
❯ ts plugin install setting --target tmc
[i] Refreshing plugin inventory cache for "projects.registry.vmware.com/tanzu_cli/plugins/plugin-inventory:latest", this will take a few seconds.
[i] Reading plugin inventory for "projects.registry.vmware.com/tanzu_cli/plugins/plugin-inventory:latest", this will take a few seconds.
\ Installing plugin 'setting:v0.2.13' with target 'mission-control'
```
```release-note
```
=> UX: Updated the output writer with text format

config/types/clientconfig_sorter.go, config/types/clientconfig_sorter_test.go
This PR adds a sorter for the Context type to sort contexts, first by context name and then by context type.
Fixes #
1) Unit tests are added
2) Manual test output:
Before fix: Context's are not sorted by name:
After fix: Context's are sorted by name:
```release-note
```
=> Add Context sorter to sort by context name then target

component/output_spinner.go, component/output_spinner_test.go, log/log.go, log/logger.go, log/types.go, log/writer.go
This PR updates the existing spinner constructor to pass spinner options to set the spinner text and final text. A new spinner API has also been introduced to set the final text while the spinner is running.  
The spinner options and API allow prefixing the final text with a logger indicator like INFO, WARN, ERROR, SUCCESS and OUTPUT. This shows the type of log message.  
The runtime log API has been updated to accommodate these logger types. The spinner options and updated API provide more flexibility to display formatted status messages to the user.
Fixes #
1. Unit test cases have been added.
2. Manual testing was performed for the following use case: The CLI Core uses the runtime API to set the spinner text displayed during plugin installation. It also sets a final spinner message …
=> Update spinner API to accept spinner options and spinner text

component/output_spinner.go, component/output_spinner_test.go
This PR is to rename the spinner API `WithSpinnerFinalMsg` to `WithSpinnerFinalText`
Fixes #
Manual testing has done to install plugins by using the updated runtime spinner api:
```release-note
```
=> Fix: Update spinner api

config/tanzu_context.go, config/tanzu_context_test.go, config/types/clientconfig_types.go
- Support requesting CustomPath endpoint for kubeconfig with `GetKubeconfigForContext` API
- Add `KubeConfigBytes` to the `KubernetesDiscovery` struct
Fixes #
```release-note
Support requesting CustomPath endpoint for kubeconfig with GetKubeconfigForContext API
```
=> Support requesting CustomPath endpoint for kubeconfig with GetKubeconfigForContext API

log/log.go, log/logger.go, log/logger_test.go
- Logger not picking the latest os level env variables
- Since the logger instance is created once any dynamic env variables set for TANZU_CLI_LOG_LEVEL are not picked by the logger causing desired log levels not printing.
Fixes #
-Manual testing the tanzu cli with logging custom log levels
```
**Case 1 :-**
In Tanzu CLI
log.SetVerbosity(4)
log.V(6).Info("testing logger with 6")
mpanchajanya@mpanchajanF09MK ~/v/r/tanzu-cli (bug-fix/cert-update)> tz config get
clientOptions:
features:
global:
context-target-v2: "true"
env:
any-plugin: baarr
cli:
ceipOptIn: "true"
eulaStatus: accepted
discoverySources:
- oci:
name: default
image: projects.registry.vmware.com/tanzu_cli/plugins/plugin-inventory:latest
cliId: 736bddac-be88-4084-a00d-137a4972b487
telemetry:
source: …
```
=> Implement sync threshold values set using env variable TANZU_CLI_LOG_LEVEL

component/README.md, component/output_spinner.go, component/output_spinner_test.go
- Refactors Spinner component to eliminate use of parameters and uses `OutputWriterSpinnerOptions` to create Spinner
- Add `SetText` and `StartSpinner` APIs
Fixes #
- Manual Testing
```release-note
`NewOutputWriterSpinnerWithOptions` is being deprecated in favor of the more flexible `NewOutputWriterSpinner` implementation.
`NewOutputWriterSpinner` now supports `SetText` and `StartSpinner` APIs.
```
=> Refactor Spinner component and Add `SetText` and `StartSpinner` APIs

plugin/plugin_test.go, plugin/types.go
Introduce two additional fields in the PluginDescriptor, InvokedAs and SupportedContexttype, marked experimental are added to support plugin level remapping
Fixes #
```release-note
Introduce two experimental fields in the PluginDescriptor, InvokedAs and SupportedContexttype to support plugin-level remapping
```
=> Augment PluginDescription with fields used in remapping commands

plugin/root.go, plugin/usage.go, plugin/usage_test.go
When a plugin is mapped via PluginDescriptor.InvokedAs, set the command display name annotation introduced in cobra 1.8.0. This enables the runtime to construct more accurate usage text based on the the mapped command name instead. 
In the future the mapping could also be provided out-of-band by the caller binary (Tanzu CLI).
Also, updated aliases computation in the usage output to take advantage of said annotation.
Behavior of the toplevel and command-specific help of plugin (e.g. appsv2 here, mapped to apps) built with runtime ..
Before the change:
```
tanzu-cli (main)> tanzu apps
Application on Kubernetes
Usage:
tanzu appsv2 [command]
tanzu kubernetes appsv2 [command]
Aliases:
appsv2, app
Available Commands:
apply                Apply the app from the files in the filepath …
```
=> Set command displayname annotation when command is mapped

component/README.md, component/output.go, component/output_spinner.go, component/output_test.go
- Add support for dynamic columns with the OutputWriter's `TableOutputType` output format
- Example usage:
```
outputPluginWriter := component.NewOutputWriterWithOptions(writer, component.TableOutputType, []component.OutputWriterOption{})
outputPluginWriter.SetKeys("Name", "Description", "Target", "Installed", "Recommended", "Status")
outputPluginWriter.MarkDynamicKeys("Recommended")  // Marking this column as dynamic so that it will only be shown if at least one row is non-empty
```
Fixes #
- Added unit test
```release-note
Add support for dynamic columns with the OutputWriter's `TableOutputType` output format
```
=> Add support for dynamic columns with the OutputWriter's `TableOutputType` output format

config/tanzu_context.go, config/tanzu_context_test.go
This PR updates the SetTanzuContextActiveResource() API to accept the Project ID along with Project Name to set a Project as active in the Tanzu context. The GetTanzuContextActiveResource API is also updated to return the Project ID along with Project Name for an active project
Fixes #
Tested with below Unit test and made sure the CLI context is updated with Project ID and Project Name.
```
func TestSetTanzuContextActvResource(t *testing.T) {
os.Setenv("TANZU_BIN", "/Users/pkalle/projects/tanzu-cli/artifacts/darwin/amd64/cli/core/v1.3.0-dev/tanzu-cli-darwin_amd64")
resInfo := ResourceInfo{
OrgID: "b1d48027-bb69-4a56-a5b8-e941ef29fa4b",
ProjectName: "unitel-project-ab",
ProjectID:   "6d1e2d22-5785-43d7-a6da-1102d7aba83b",
SpaceName: "store-dev",
}
err := …
```
=> Update SetTanzuContextActiveResource API and GetTanzuContextActiveResource to use Project ID along with Project Name

config/tanzu_context.go, config/tanzu_context_test.go
This PR updates `GetKubeconfigForContext` API  logic to use/accept Project ID instead of Project Name
Fixes #
```release-note
Update GetKubeconfigForContext API to accept Project ID instead of Project Name
```
=> Update GetKubeconfigForContext API to accept Project ID instead of Project Name

component/output_spinner.go
This PR updates the spinner API to store all spinners and close any that are still active when the user wants to stop the spinner after the command has completed or been interrupted. This will help ensure all spinners are properly closed.
Use case:
If the user is running `tanzu plugin sync`, it installs all the required plugins for each context. Assume that it has installed a few plugins, and now the user wants to terminate the command with Ctrl+C. In this case, the API should stop the current spinner and also check for any other active spinners and terminate them as well. This new API helps handle these types of use cases.
Fixes #
```release-note
The spinner API has been updated to track all active spinners and stop them when the command ends or is terminated by the user.
```
=> Update spinner API to stop all running spinners

config/clientconfig_test.go, config/contexts.go, config/tanzu_context.go, config/tanzu_context_test.go
This PR adds null pointer checks in APIs
Summary:
- Add null pointer checks in GetKubeconfigForContext API for ClusterOpts in context.
- Added null pointer checks in EndpointFromContext API as well
Fixes #
Unit tests and CI
```release-note
```
=> Add null pointer checks in GetKubeconfigForContext API

plugin/info.go, plugin/info_test.go, plugin/invoke_context.go, plugin/plugin_test.go, plugin/root.go, plugin/types.go, plugin/usage.go, plugin/usage_test.go
Replaces InvokedAs field in the PluginDescriptor with a list of CommandMapEntry's that can provide additional mapping details. In particular it can specify a destination command path of the Tanzu CLI to map to a specific non root command path in the plugin.
Adds support for capturing the invocation "context" by consuming environment variables that are expected to be set by the Tanzu CLI when invoking a command that is being mapped.
Information in this context allows the plugin to construct proper Help information, and learn if the its command being invoked is done via a command-level mapping or not.
Updates the usage to provides better output when help is invoked on a command-level mapping.
Some additional handling added to propagate aliases and description of a mapped subcommand. 
``` …
```
=> Extend plugin mapping to command-level remapping

plugin/invoke_context.go, plugin/invoke_context_test.go, plugin/usage.go, plugin/usage_test.go
Among the changes
- Fix usage output of a descendant command of the command-level mapped command.
- Leverage the invoked command's .Use as long as it is prefixed by the premap command name
- Update aliases list to included the mapped command name instead of the premapped one
In addition, provide a set of functions to obtain useful information about the InvocationContext
```
CLIInvocationString : return base CLI invocation string up to the mapped command
CLIInvocationStringForCommand : return full CLI invocation string that would have led to the invocation of the provided Command
MappedSourceCommandPath : returns the mapped command path used as the source of the command mapping
InvokedGroupPath : returns the command path CLI uses prior to the mapped command
InvokedCommandName : returns …
```
=> Fix usage of commands involved in command-level mapping

plugin/generate_docs.go, plugin/generate_docs_test.go, plugin/plugin.go, plugin/usage.go, plugin/usage_test.go
```   
The approach taken is to recreate the tanzu CLI command tree with only
the plugin's commands, after accounting for the mapping directives,
and hand said command tree to cobra's doc generation APIs.
```
Note: this superceds #182 (retained temporarily for reference)
* Added new unit tests to generate-docs using a Plugin with various CommandMap configuration
and verifies generated file set and expected content of the files.
* Run `plugin-binary generate-docs --docs-dir xxx` for sample plugin binaries with and without CommandMap entries and verified that a consistent set of md docs are generated
* Use Tanzu CLI (need to include https://github.com/vmware-tanzu/tanzu-cli/pull/752)'s generate-all-docs command
`tanzu generate-all-docs --docs-dir xxx` with the above mentioned sample plugin …
=> Update generate-docs to accounts for command mapping 2

plugin/usage.go, plugin/usage_test.go
If a mapped command is runnable and has flags,
make sure its useline includes the ' [flags]' suffix
Fixes #
See updated unit tests
```release-note
Ensure flags suffix is added to useline
```
=> Ensure flags suffix is added to useline

plugin/usage.go, plugin/usage_test.go
Fixes #
See updated unit tests
```release-note
Example lines for a plugin command will be produced without any additional indentation. 
Plugins should refrain from introducing their own custom indentation in any multiline Example fields of their commands.
```
=> Remove indent when generating Example lines in usage

config/contexts.go, config/contexts_test.go, config/conversion.go, config/conversion_test.go
This PR disables syncing of "tanzu" type contexts between legacy and latest CLI config files. 
Summary:
Currently when tanzu context type is created , a corresponding server entry would be created. This would result in loss of some fileds(as per the legacy server structure type). Also, this syncing is bi-directional(context <> server). If the latest CLI configuration files is deleted or messed up, the syncing of server types to context type with incomplete data would cause issues for tanzu operations. So disabling the "tanzu" context type syncing between servers) and contexts would solve this issue.
Fixes #
- Unit tests and CI
-Deleted the legacy config file and had the below latest config file (config-ng.yaml) . Now if I execute any CLI command CLI regenerated servers in the legacy …
=> Disable syncing of "tanzu" contexts between legacy and latest CLI configuration files

plugin/usage.go, plugin/usage_test.go
Now that multi-line Example values do not need explicit indent to have them shown left-aligned in usage, update usage to ensure there is at least a designated amount of indent for each non-empty line, so as to match up with the rest of the usage sections.
Also correct for some specific situations where the explicit indent of subsequent lines is still present in the Example value by making the output for such value left aligned as well.
For Command with Example values that is 
- single line, 
- multiline with no explicit indent
- multiline with explicit 2 space indent for each line or for all but the first line
The example lines will be indent by 2 spaces.
For all other multiline values with arbitrary indents, all the lines will just be indented a further 2 spaces instead
Fixes #
See …
=> Align example lines with rest of usage output

plugin/usage.go, plugin/usage_test.go
Today plugins created with TargetK8s target type have their commands visible/invocable via both `tanzu <pluginname> ...` and `tanzu kubernetes|k8s <plugingname> ...`
The form without a target prefix is available only to kubernetes target for historical and compatibility reasons, but is the predominant invocation style. Since Tanzu Platform's plugin functionality are delivered through a mix of kubernetes-targeted and nonkubernetes-targeted plugins, encouraging this more compact form is important in promoting consistent and intuitive invocation styles. 
This PR removes the invocation using the `kubernetes` target from the help output of plugins.
Note that a plugin must be recompiled with this PR for the change to take effect.  Therefore it will only start taking effect as new versions of …
=> Remove invocation with "kubernetes" in the help

plugin/info_test.go, plugin/types.go
This provides explicit control at a command map entry level on whether the mapping should take effect conditionally on the type of context that is active.
Fixes #
```release-note
CommandMapEntry supports a RequiredContextType list, which controls whether the mapping should take effect based on the type of the active context.  
```
=> Add per-mapping required context type

component/README.md, component/prompt.go, component/prompt_test.go, component/select.go
An useful extension to both the Prompt and Select component. The usage of the component is unchanged. However, providing a slice of strings to record answers from a list of selected options will enable multiple selection of said options.
Updated unit tests + manual testing, using a test command exercising the multiselect functionality, shown below
[![asciicast](https://asciinema.org/a/Gz1UhQqMq8G1OX9OZPRKtfSFn.svg)](https://asciinema.org/a/Gz1UhQqMq8G1OX9OZPRKtfSFn)
```release-note
Enable multi selection in Prompt and Select components.
```
=> Enable multi selection support in Prompt and Select components

component/output.go, component/output_test.go
- Fix OutputWriter Table to show rows when no headers are specified
- This will make sure that we support Tables without headers as well.
Fixes #
- Added unit tests
```release-note
Fix OutputWriter Table to show rows when no headers are specified
```
=> Fix OutputWriter Table to show rows when no headers are specified

plugin/usage.go, plugin/usage_test.go
- This PR fixes the help text generation issue when `non-global` target plugin remaps the commands.
Before this change:
- Target information was shown even if the command gets remapped to the root level
After this change:
- Target information will not be used to show command help text if the command is remapped
Fixes #
- Manual Testing
- Unit Test
```release-note
Fix plugin command usage when the `mission-control`/`operations` target plugin remaps the commands 
```
=> Fix plugin command usage when the `mission-control`/`operations` target plugin remaps the commands 

client/hub/testing/README.md, client/hub/testing/operations.go, client/hub/testing/server.go
This PR updates the `README` for the graphql testing framework as well as some comments here and there.
Also it fixes two error situations where the mock server would send more than one response because of the use of `break` instead of `return`.
Fixes # N/A
CI
```release-note
Update graphql testing README.
```
=> Update to graphql testing doc

client/hub/client_test.go, client/hub/testing/operations.go, client/hub/testing/server.go, client/hub/types.go
- Support throwing errors for Query and Mutations
- Make `OperationName` optional when sending requests
- Make mock response more flexible to return by implementing the `Responder` function which includes the mock variables
Fixes #
```release-note
Make OperationName optional for Hub Client requests. Improvements to the Hub client unit test framework
```
=> Improvements to Hub client unit testing framework

config/clientconfignextgen_lock.go, config/lock.go, config/metadata_lock.go
**Background:**
- As part of https://github.com/vmware-tanzu/tanzu-plugin-runtime/pull/200 we switched to use `github.com/alexflint/go-filemutex` package instead of `github.com/juju/fslock`.
- The `Unlock` function between the two libraries behaves differently. The main difference is the `go-filemutex.Unlock` does not close the file whereas the `fslock.Unlock` does close the file, automatically releasing any acquired lock.
- Because of the above difference we noticed that when the following sequence of operations are performed the acquiring the lock fails because the file was kept open by the first lock call.
- `go-filemutex.Lock`
- `go-filemutex.Unlock` 
- `fslock.Lock`
- The above behavior can be noticed when the Tanzu CLI uses `go-filemutex` to lock the file using newer version of …
=> Fix file lock issue on windows

component/select.go
When we use [SelectConfig.Run(..)](https://github.com/vmware-tanzu/tanzu-plugin-runtime/blob/de610f924174d2584815f72ae1298277ccf387c6/component/select.go#L34) we should be able to pass PrompOpt.. as argument similar to [PromptConfig](https://github.com/vmware-tanzu/tanzu-plugin-runtime/blob/de610f924174d2584815f72ae1298277ccf387c6/component/prompt.go#L37). When we're not able to do this interactive testing for MultiSelect becomes impossible.
Fixes #207 
```release-note
Add PrompOpt parameter to SelectConfig.Run() method. This allows SelectConfig to have behaviour similar to PromptConfig
```
The issue is tracked down also in VMware Jira: TANZU-9559
=> Add prompt opts to SelectConfig.Run

client/hub/client.go, config/certs.go, config/certs_test.go, docs/config.md
- The Hub Client will use the `GetCert` API to get the certificate data for the specified hub endpoint.
- If the certificate data is not found, it will skip the TLS configuration and let the client use default configuration.
- GetCert API now accepts URI along with hostname
Fixes #
```release-note
Support Self-Signed CA Cert and skip-cert-verify with Hub Client
GetCert API now accepts URI along with hostname
```
=> Support Self-Signed CA Cert and skip-cert-verify with Hub Client

client/hub/client.go
- Fix incorrect base64 encoded caCert usage with Hub Client
Fixes #
```release-note
None
```
=> Fix incorrect base64 encoded caCert usage with Hub Client

client/hub/client.go
=> [Cherry-pick 1.4] Fix incorrect base64 encoded caCert usage with Hub Client (#212)

component/prompt.go, component/prompt_test.go, hack/check/check-mdlint.sh
Tanzu services plug-ins requires more multiline input for operations like configuring preprovisioned services with certificates.
Fixes #
Written unit tests + manual testing of survey.Multiline
```release-note
Support `multiline = true` to PromptConfig and be able to add multiline strings as prompt inputs.
```
=> add multiline prompt config support

client/hub/client_test.go, client/hub/testing/operations.go, client/hub/testing/server.go
Before this PR the UT framework would send the registered operation.  This was not useful for unit tests as it is those same tests that registered the operation, so they are aware of what it is.  What the tests need is for the framework to send the actual received GraphQL request so that it can be verified. 
This PR does this.
NOTE: This change is not backwards-compatible.  However, I feel it is early enough in the use of the UT framework and that the only ones using it are probably the CLI team, that we can easily adapt.
The unit tests of the UT framework are updated to check that the sent value is the actual query received by the mock server.
Follow-up to #202 
I have an internal set of unit tests that now detects more failures by comparing the received graphql request with what the …
=> The Hub UT framework should send what it received

component/prompt.go, component/prompt_test.go, hack/check/check-mdlint.sh
Cherry-pick: https://github.com/vmware-tanzu/tanzu-plugin-runtime/pull/216
---------
* add multiline response support
* update mdlint with present docker image
Fixes #
```release-note
Support `multiline = true` to PromptConfig and be able to add multiline strings as prompt inputs.
```
=> [Release-1.4] CherryPick: Add multiline prompt config support

client/hub/client_test.go, client/hub/testing/operations.go, client/hub/testing/server.go
Cherry-pick: #206
Before this commit the UT framework would send the registered operation. This was not useful for unit tests as it is those same tests that registered the operation, so they are already aware of what it is.  What the tests need is for the framework to send the actual received GraphQL request so that it can be verified. This commit does this.
Fixes #
```release-note
Hub unit test framework now sends back the GraphQL request it received for more thorough testing.  This change breaks backwards-compatibility of the API used to write unit test for GraphQL: the `Responder` and `EventGenerator` types have a slightly different signature.
```
=> [Release-1.4] CherryPick: Have the Hub UT framework send what it received

client/hub/request.go
Cherry-pick: (#219)
Fixes #
```release-note
Increases the GraphQL subscription client buffer size to 1MB to handle larger event chunks 
```
=> [Release-1.4] Increases the GraphQL subscription client buffer size to 1MB to handle larger event chunks

plugin/root.go, plugin/root_test.go, plugin/usage.go
This PR is on top of #227 so that the new test that checks for dead-code elimination works (or else the old Cobra version would prevent dead-code elimination and the test would fail).
When templating is used, the linker cannot know which functions are called and which one are not; this is because templating use calls to `MethodByName()` which can be used to call any function (similar to reflection). 
With the release of Cobra 1.9.1, templates are no longer used by default in Cobra. By also not using templates in the tanzu-plugin-runtime it now gives an opportunity for plugins to try to avoid templates to allow dead-code elimination to work, if they so choose.
This PR therefore removes the use of templates in tanzu-plugin-runtime.
Note that we had technically already moved to using go code …
=> Don't use templating to allow for dead-code elimination
